env: dev
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/CertificateValidator
        username: root
        password: Sanbro@2000
    jpa:
        hibernate:
            ddl-auto: update
        sql: true
        properties:
            hibernate:
                format_sql: true
        
